#!/bin/bash
#Initial wifi interface configuration
 
DIR=$(dirname $0)
if [ -e "$DIR/disable_ap" ]
then
   echo "disabled AP by disable_ap file in $DIR"
   exit 0
fi
 
CONF=$1
APIF=$2
WAN=$3
 
ifconfig $APIF up 10.10.10.1 netmask 255.255.255.0
sleep 2
###########Start DHCP##########
killall dhcpd
sleep 1
if [ "$(ps -e | grep dhcpd)" == "" ]; then
        dhcpd $APIF &
fi
###########
#Enable NAT
iptables --flush
iptables --table nat --flush
iptables --delete-chain
iptables --table nat --delete-chain
iptables --table nat --append POSTROUTING \
            --out-interface $WAN -j MASQUERADE
iptables --append FORWARD --in-interface \
           $APIF -j ACCEPT
 
sysctl -w net.ipv4.ip_forward=1
#start hostapd
/usr/sbin/hostapd -B $CONF